version: "3.8"

services:
  postgres:
    image: postgres
    container_name: bike_share_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bike_share_db
    ports:
      - "5432:5432"
