version: "3.8"

services:
  db:
    image: postgres
    container_name: bike_share_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bike_share_db
    ports:
      - "5432:5432"

  cache:
    image: redis
    container_name: bike_share_redis
    restart: always
    environment:
      REDIS_PASSWORD: "EiYAZzjMCSEMjd0sC81I9IUzpRcv53FE"
    ports:
      - "6379:6379"
